meta_product_name: "The Menu"
meta_title: "The Menu - What's on the Menu tonigth?"
meta_description: "Relevant description"
meta_image: "chief-photo.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards